### ISSUE TITLE
when /soupffa qui

### ISSUE THREAD

**Issue by armagadon159753** [McpeBooster/SoupFFA-McpeBooster#2]
underfined variable line 270.

![screenshot_2017-07-11-19-02-55](https://user-images.githubusercontent.com/25569806/28080279-b26c35a0-666b-11e7-83cf-fe2d1f186d91.png)

**Comment by McpeBooster** [comment]
It's fixed now, thanks for your infomation :D

**Comment by armagadon159753** [comment]
^°^ thx
