### ISSUE TITLE
Sign doesn't work

### ISSUE THREAD

**Issue by armagadon159753** [McpeBooster/SoupFFA-McpeBooster#3]
"You can not join the ffa soup" when i tap on the sign

**Comment by McpeBooster** [comment]
Have you set up the arena correctly?

**Comment by armagadon159753** [comment]
@McpeBooster yes only command work

**Comment by armagadon159753** [comment]
I have test 
Only 1.5.0 work fine with signe 
Same config.yml
Same map

**Comment by McpeBooster** [comment]
Does the sign work with my KnockbackFFA plugin?

**Comment by armagadon159753** [comment]
@McpeBooster when I type the sign I am correctly teleporting

**Comment by McpeBooster** [comment]
Maybe try to set up soupffa completely new

**Comment by armagadon159753** [comment]
OK i will try that

**Comment by armagadon159753** [comment]
i check everything that doesnt work

**Comment by McpeBooster** [comment]
Blame me!

It should be fixed now :D



get the phar: http://McpeBooster.tk/plugins
