### ISSUE TITLE
I have a Problem

### ISSUE THREAD

**Issue by chaosfreak93** [McpeBooster/SoupFFA-McpeBooster#8]
03:01:49 CRITICAL > Could not pass event 'pocketmine\event\block\BlockPlaceEvent' to 'SoupFFA v3.0.0': Class 'SoupFFA\Listener\SoupFFA' not found on SoupFFA\Listener\onPlace         03:01:49 CRITICAL > Error: "Class 'SoupFFA\Listener\SoupFFA' not found" (EXCEPTION) in "plugins/SoupFFA-McpeBooster/src/SoupFFA/Listener/onPlace" at line 20
03:01:49 DEBUG > #0 src/pocketmine/plugin/MethodEventExecutor(38): SoupFFA\Listener\onPlace->onPlace(pocketmine\event\block\BlockPlaceEvent object)
03:01:49 DEBUG > #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(SoupFFA\Listener\onPlace object, pocketmine\event\block\BlockPlaceEvent object)
03:01:49 DEBUG > #2 src/pocketmine/plugin/PluginManager(688): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\block\BlockPlaceEvent object)
03:01:49 DEBUG > #3 src/pocketmine/level/Level(1928): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\block\BlockPlaceEvent object)
03:01:49 DEBUG > #4 src/pocketmine/Player(2322): pocketmine\level\Level->useItemOn(pocketmine\math\Vector3 object, pocketmine\item\Sign object, integer 1, pocketmine\math\Vector3 object, SoupFFA\Player\SoupPlayer object, boolean 1)
03:01:49 DEBUG > #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(133): pocketmine\Player->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
03:01:49 DEBUG > #6 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(148): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
03:01:49 DEBUG > #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(93): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
03:01:49 DEBUG > #8 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
03:01:49 DEBUG > #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(93): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
03:01:49 DEBUG > #10 src/pocketmine/Player(3026): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
03:01:49 DEBUG > #11 src/pocketmine/network/mcpe/RakLibInterface(149): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
03:01:49 DEBUG > #12 vendor/pocketmine/raklib/server/ServerHandler(103): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 91.48.64.41 51989, raklib\protocol\EncapsulatedPacket object, integer 0)
03:01:49 DEBUG > #13 src/pocketmine/network/mcpe/RakLibInterface(88): raklib\server\ServerHandler->handlePacket()
03:01:49 DEBUG > #14 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
03:01:49 DEBUG > #15 src/pocketmine/Server(2594): pocketmine\network\Network->processInterfaces()
03:01:49 DEBUG > #16 src/pocketmine/Server(2345): pocketmine\Server->tick()
03:01:49 DEBUG > #17 src/pocketmine/Server(2218): pocketmine\Server->tickProcessor()
03:01:49 DEBUG > #18 src/pocketmine/Server(1805): pocketmine\Server->start()
03:01:49 DEBUG > #19 src/pocketmine/PocketMine(385): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/Lobby/, string /root/Lobby/plugins/)

Thats ist the Error Code!

**Comment by McpeBooster** [comment]
It's fixed!
